<a href="https://colab.research.google.com/github/lax17/PyTorch/blob/master/Mathematical_Operations_in_PyTorch(vs_NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing PyTorch

In [0]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1MB 26kB/s 
     |████████████████████████████████| 8.8MB 36.6MB/s 
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
  Found existing installation: torchvision 0.6.0+cu101
    Uninstalling torchvision-0.6.0+cu101:
      Successfully uninstalled torchvision-0.6.0+cu101


In [0]:
import numpy as np
import torch

**Mathematical Operations in PyTorch(vs. NumPy)**

In [7]:
'''We will initialize two arrays and then perform mathematical operations like addition, subtraction, multiplication, and division, on them:'''
# initializing two arrays
a = np.array(2)
b = np.array(1)
print(a,b)   
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

# initializing two tensors
a = torch.tensor(2)
b = torch.tensor(1)
print(a,b)
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)



2 1
3
-1
2
2.0
tensor(2) tensor(1)
tensor(3)
tensor(-1)
tensor(2)
tensor(2)


**Matrix Operations in PyTorch(vs. NumPy)**

*Matrix* *Initialization*

In [0]:
'''Let’s say we want a matrix of shape 3*3 having all zeros. Take a moment to think – how can we do that using NumPy?'''

a = np.zeros((3,3))
print(a)
print(a.shape) 

'''Fairly straightforward. We just have to use the zeros() function of NumPy and pass the desired shape ((3,3) in our case), and we get a matrix consisting of all zeros. Let’s now see how we can do this in PyTorch:'''

a = torch.zeros((3,3))
print(a)
print(a.shape) 


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [0]:
'''Now, while building a neural network, we randomly initialize the weights for the model. 
So, let’s see how we can initialize a matrix with random numbers:'''
# setting the random seed for numpy
np.random.seed(42)
#matrix of random numbers
a = np.random.randn(3,3)
print(a)
# setting the random seed for pytorch
torch.manual_seed(42)
a = torch.randn(3,3)
print(a)

'''This is where even more similarities with NumPy crop up.
 PyTorch also has a function called randn() that returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).'''

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


*Matrix* *Operation*

In [0]:
# setting the random seed for numpy and initializing two matrices
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

# matrix addition
print(np.add(a,b), '\n')

# matrix subtraction
print(np.subtract(a,b), '\n')
 
# matrix multiplication
print(np.dot(a,b), '\n')
 
# matrix multiplication
print(np.divide(a,b))

# setting the random seed for pytorch and initializing two tensors
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
# matrix addition
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication
print(torch.mm(a,b), '\n')

# matrix division
print(torch.div(a,b))
'''Note that the .mm() function of PyTorch is similar to the dot product in NumPy. 
This function will be helpful when we create our model from scratch in PyTorch. '''

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]]
tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [0]:
'''Matrix transpose is one technique which is also very useful while creating a neural network from scratch.
 So let’s see how we take the transpose of a matrix in NumPy:'''

 # original matrix
print(a, '\n') 

# matrix transpose
print(np.transpose(a))

# original matrix
print(a, '\n')

# matrix transpose
print(torch.t(a))


tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


Concatenating Tensors

In [10]:
# initializing two tensors
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)

'''What if we want to concatenate these tensors vertically? We can use the below code:'''
# concatenating vertically
print(torch.cat((a,b)))

'''As you can see, the second tensor has been stacked below the first tensor.
 We can concatenate the tensors horizontally as well by setting the dim parameter to 1:'''
 
# concatenating horizontally
print(torch.cat((a,b),dim=1))

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


*Reshaping* *Tensors*

In [12]:
# setting the random seed for pytorch
torch.manual_seed(42)
# initializing tensor
a = torch.randn(2,4)
print(a)
print(a.shape)

'''We can use the .reshape() function and pass the required shape as a parameter. 
Let’s try to convert the above tensor of shape (2,4) to a tensor of shape (1,8):'''

b = a.reshape(1,8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])
torch.Size([2, 4])
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

Awesome! PyTorch also provides the functionality to convert NumPy arrays to tensors. You can use the below code to do it:

In [13]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


**Common PyTorch Modules**

**Autograd** **Module**

The autograd module helps us to compute the gradients in the forward pass itself which saves a lot of computation time of an epoch.

In [0]:
# initializing a tensor
a = torch.ones((2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [0]:
b = a + 5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [0]:
# back propagating
c.backward() 

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


**Optim** **Module**

The Optim module in PyTorch has pre-written codes for most of the optimizers that are used while building a neural network. We just have to import them and then they can be used to build models.

In [0]:
# importing the optim module
from torch import optim

# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)

# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)

**nn** **Module**

In [0]:
# The autograd module in PyTorch helps us define computation graphs as we proceed in the model. 
# But, just using the autograd module can be low-level when we are dealing with a complex neural network.

# In those cases, we can make use of the nn module. 
# This defines a set of functions, similar to the layers of a neural network, which takes the input from the previous state and produces an output.